### ISSUE TITLE
git install: appindicator shows "@PROGRAM_NAME@"

### ISSUE THREAD

**Issue by cweiske** [osdlyrics/osdlyrics#26]
When compiling osdlyrics from git, installing and running it I get the following appindicator:

```
[icon] @PROGRAM_NAME@
(songdetails)
```

That `@PROGRAM_NAME@` should probably replaced with "osdlyrics".

![2017-07-10 osdlyrics appindicator](https://user-images.githubusercontent.com/59036/28017492-ccb09ad4-6579-11e7-9872-fa7f052e8327.png)

**Comment by Corax26** [comment]
Good catch, looks like it's been broken for a very long time, `daemon/config.py.in`relies on an M4 macro that's not defined. However I'm not very familiar with autoconf and I'm struggling to find the proper fix for this, I saw that `configure.ac` defines `PROGRAM_NAME` using `AC_DEFINE`, which is not right because this only defines a C macro, but I'm not sure how to make autoconf define an M4 macro as well...
