### ISSUE TITLE
Brainstorm: AppIndicator vs GtkStatusIcon

### ISSUE THREAD

**Issue by Corax26** [osdlyrics/osdlyrics#35]
For quite some time, I had been wondering where the feature I had implemented to change the delay by scrolling on the tray icon (87756001396ce287252a6e72b8fa5e0889c7868f) had gone. As I now have a bigger screen and leave the OSD enabled much more often, this really started bugging me, so I investigated. Fortunately, that didn't take long: the issue was simply that I installed libappindicator-gtk2 at some point, and therefore I was now using the AppIndicator implementation of ol_trayicon.c!

This made me realise that we have much more features when implementing the tray icon with GtkStatusIcon than with AppIndicator (see [ol_trayicon.c:162](https://github.com/osdlyrics/osdlyrics/blob/master/src/ol_trayicon.c#L162)). At this point the question is: should we really implement it with AppIndicator if libappindicator is available? AFAICT, we should only do that if GtkStatusIcon doesn't work under the DE we're compiling for. Apparently, there are two of them in that case: Unity and KDE.

There doesn't seem to be an obvious solution there, as I don't think you can easily detect which DE is being used, and it's not clear it's a good idea anyway. Alternatively, maybe we could make it mandatory to choose one or the other option at configure-time? In both cases, this doesn't solve the problem for packagers, who would basically need to maintain two packages.

Any thoughts? Maybe @tigersoldier could clarify the situation, since he added the AppIndicator implementation.

**Comment by tigersoldier** [comment]
I added app indicator support for Ubuntu users, with the assumption that only Ubuntu provides such library and most of the Ubuntu users use unity.

App indicator supports the Ubuntu indicators natively. Unity had some different ux for indicators. For example when you open the menu of one indicator and move your pointer over another indicator, the menu of the indicator under the pointer opens.

Because of that reason, I thought it's a better user experience to use app indicator on unity. This may still be true today, but unity is deprecated.

Back to the topic, I think the best approach is to make the decision of whether to use app indicator at runtime, not compile time. I have 2 options in mind:

1. Check whether the current de is unity. If yes, use app indicator, otherwise, don't use it.
2. Add a preference on whether to use it or not.

Option 1 is easier to implement. It only requires reading environment variables, not adding UI elements. It's likely to work better for users that switch de between unity and others often. The only drawback is unity users still don't have access to the scrolling feature you added.

A third option is removing app indicator. This is the easiest way but it's an regression IMO.

I don't get why gtkstatusicon doesn't work on KDE. It's just a wrapper around standard x protocol. It worked fine last time I tested on KDE.

**Comment by Corax26** [comment]
I briefly thought of checking the current DE at runtime, but I wasn't sure how easy that would be. Actually that seems to be pretty simple, using `XDG_CURRENT_DESKTOP`, looks like another project had exactly the same problem as us and considered using this variable: https://github.com/syncthing/syncthing-gtk/issues/73 (the issue also mentions that GtkStatusIcon support has been dropped in KDE 5).

So I guess we could do something along these lines:
1. If configured with `--enable-appindicator=yes/no`, then use the corresponding library and don't do runtime detection.
2. If configured with `--enable-appindicator=auto` (default) and libappindicator is not available, then again we can only use GtkStatusIcon.
3. If configured with `--enable-appindicator=auto` and libappindicator is available, then choose the implementation at runtime based on `XDG_CURRENT_DESKTOP`.

Does that sound reasonable?

**Comment by PedroHLC** [comment]
> If configured with --enable-appindicator=auto and libappindicator is available, then choose the implementation at runtime based on XDG_CURRENT_DESKTOP. 

as long as this constraint is not violated, your idea seems the best choise.

**Comment by tigersoldier** [comment]
> If configured with --enable-appindicator=auto and libappindicator is available, then choose the implementation at runtime based on XDG_CURRENT_DESKTOP.

`XDG_CURRENT_DESKTOP` should be quite reliable. You can use `HAVE_APP_INDICATOR` to enable runtime detection, regardless the value of `--enable-appindicator` (`HAVE_APP_INDICATOR` is derived from this option and the availability of app indicator library).

**Comment by Corax26** [comment]
> You can use HAVE_APP_INDICATOR to enable runtime detection, regardless the value of --enable-appindicator (HAVE_APP_INDICATOR is derived from this option and the availability of app indicator library).

Well actually that's a slightly different behaviour. My original idea is to do the runtime detection only if `--enable-appindicator=auto`, something which `HAVE_APP_INDICATOR` doesn't tell you.

So I think there are two options here:
1. Always do runtime detection if libappindicator support is compiled in.
2. Only do runtime detection if OSD Lyrics was configured with `--enable-appindicator=auto`.

The rationale behind the second option is that if you configure with `--enable-appindicator=yes`, then it means you actually want to use libappindicator. Is that a good assumption? Otherwise, if we go for option 1, then I'd rather rename the configure option to something like `--enable-appindicator-support` (to highlight the fact that whether libappindicator is used or not is a runtime decision).

**Comment by tigersoldier** [comment]
This makes sense. I prefer `--enable-appindicator-support`. The code is cleaner and easier to maintain.

**Comment by Corax26** [comment]
OK sounds good to me, thanks for your input @tigersoldier. If there's no further suggestion I hope to look into implementing that within the next few weeks (this may get pushed back though, right now I'm looking into fixing some stuff with the OSD, #36 being something I discovered by accident while looking into some weird behaviour of the OSD).

**Comment by firstuanl** [comment]
声音indicator的图标是在哪里控制的，我用的是unity,结果出来好大的图标
