### ISSUE TITLE
Request: Support MOCP

### ISSUE THREAD

**Issue by aasutossh** [osdlyrics/osdlyrics#40]
My player of choice is mocp, so I wanted to know if mocp is supported with osdlyrics.

**Comment by Corax26** [comment]
Apologies for the (very) late reply :/ The shortest answer is: if it supports [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) (either v1 or v2), then yes, otherwise it will require special support in OSD Lyrics. Many players have plugins for talking via MPRIS, not sure about mocp.

**Comment by PedroHLC** [comment]
Hello @DrDonkeym, do you have any updates on this? Did  MOCP get MPRIS support? Or did you tested the fork?

**Comment by DrDonkey** [comment]
@PedroHLC No I didn't. I just used mocp when I just wanted music, and that is most of the time. For lyrics I used Clementine+osd.

Anyway now I am on ncmpcpp+mpd.
