### ISSUE TITLE
Request: Milestone/Status of a new version/release.

### ISSUE THREAD

**Issue by sassmann** [osdlyrics/osdlyrics#54]
Last release (0.4.3) is from 2012.
Maybe it's time for 0.4.4 or 0.5.0? :)

**Comment by PedroHLC** [comment]
Hello @sassmann

Since 2013, tiger (the author) could no longer maintain OSDLyrics, in 2017 he swapped project management to the actual community. While this happened, v0.5 was in development, replacing parts of C code with Python 2 code. Not every feature transition was finished and without anyone actively working on it everything got stuck.
In the new community's repository, we manage to unite different efforts fixing and enhancing both stable and in-development branches. But with no dedicated collaborator, it's too hard planning and/or coordinating new features and releases.
Also, Python 2 is [currently dying](https://pythonclock.org), this puts the in-dev branch in a hard place, as work is required to move it to Python 3 (some PRs were already submitted for this).
Even then, we'll still need to finish implementing things in-dev, fix open issues and check if things are up-to-date with GTK/D-Bus/and others dependencies.

But, if other collaborators are interested, we could put an EPIC/Milestone for an actual 1.0 release, maybe even recruit committers with events like hacktoberfest, summer code, etc...

**Comment by sassmann** [comment]
Thanks for the detailed feedback.
What you're saying makes perfectly sense. All I can add is a that new Milestone might bring attention back to the project and also triggers distros to maybe update their packages. So if things aren't totally broken it should benefit the project.

**Comment by PedroHLC** [comment]
I'll try keep things updated within GitHub project pages
